apiVersion: apps/v1
kind: Deployment
metadata:
  name: ek
  labels:
    app: ek
spec:
  selector:
    matchLabels:
      app: ek
  template:
    metadata:
      labels:
        app: ek
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.1.1
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          hostPort: 9200
      - name: kibana
        image: kibana:8.1.1
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
          hostPort: 5601
        startupProbe:
          httpGet:
            path: /
            port: 5601
          failureThreshold: 10
          periodSeconds: 30
